### ISSUE TITLE
Clojure v1.10.1 Has Been Released

### ISSUE THREAD

**Issue by felicianotech** [Quantisan/docker-clojure#68] opened 2019-09-20 12:25 UTC
Can we get an updated image for this?

https://clojure.org/news/2019/06/06/clojure1-10-1

**Comment by cap10morgan** [comment] 2019-09-21 15:45
Yes, we need to rework our build system for the upstream changes to the Java images. I'll hopefully get to that soon.

**Comment by cap10morgan** [comment] 2019-09-21 16:51
This is effectively a dupe of #66 since Clojure itself is a dependency. We package build tools that can install more or less any version of Clojure. But we do also pre-download the latest stable Clojure release into the image for convenience, optimization, and offline usage. So I'll treat this issue as my reminder to bump that to 1.10.1 once our upstream build issues are sorted out.

**Closed** 2019-09-24 14:34 UTC

**Comment by felicianotech** [comment] 2019-10-16 16:00
Thank you.
